// Generated by CoffeeScript 1.6.3
(function() {
  var initialize_tinymce, tinymce_defaults;

  tinymce_defaults = {
    selector: '.st-text-block',
    inline: true
  };

  initialize_tinymce = function(block) {
    var $text, config;
    config = $.extend(tinymce_defaults, {
      selector: "#" + block.blockID + " .st-text-block"
    }, _.result(SirTrevor, 'tinymce_config') || {}, _.result(block.sirTrevor.options, 'tinymce_config') || {}, _.result(block, 'tinymce_config') || {});
    tinymce.init(config);
    if ($text = typeof block.getTextBlock === "function" ? block.getTextBlock() : void 0) {
      $text.trigger('blur');
      if ($text.is('[contenteditable]')) {
        return $text.trigger('focus');
      }
    }
  };

  SirTrevor.EventBus.bind('block:create:new', initialize_tinymce);

  SirTrevor.EventBus.bind('block:create:existing', initialize_tinymce);

  SirTrevor.Block.prototype._initTextBlocks = function() {
    return initialize_tinymce(this);
  };

  SirTrevor.EventBus.bind('block:remove:pre', function(block) {
    return tinymce.remove("#" + block.blockID);
  });

  SirTrevor.toMarkdown = function(html) {
    return html;
  };

  SirTrevor.toHtml = function(html) {
    return html;
  };

}).call(this);

/*
//@ sourceMappingURL=tinymce-plugin.map
*/
